// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import "go.mongodb.org/mongo-driver/bson/primitive"

type Author struct {
	ID    string  `bson:"_id,omitempty" json:"id"`
    Name  string  `bson:"name" json:"name"`
    Email string  `bson:"email" json:"email"`
    BookIDs []primitive.ObjectID `bson:"bookIds" json:"bookIds"`
	Books   []*Book             `bson:"books" json:"books,omitempty"`
}

type AuthorInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Book struct {
	ID        string     `bson:"_id,omitempty" json:"id"`
    Title     string     `bson:"title" json:"title"`
    Isbn      string     `bson:"isbn" json:"isbn"`
	AuthorIds   []primitive.ObjectID `bson:"authorIds" json:"authorIds"`
	PublisherID primitive.ObjectID `bson:"publisherId" json:"publisherId"`
    Authors   []*Author  `bson:"authors,omitempty" json:"authors"`
    Publisher *Publisher `bson:"publisher,omitempty" json:"publisher"`
}

type BookInput struct {
	Title       string   `json:"title"`
	Isbn        string   `json:"isbn"`
	AuthorIds   []string `json:"authorIds"`
	PublisherID string   `json:"publisherId"`
}

type Mutation struct {
}

type Publisher struct {
	ID       string  `bson:"_id,omitempty" json:"id"`
    Name     string  `bson:"name" json:"name"`
    Location string  `bson:"location" json:"location"`
	BookIDs []primitive.ObjectID `bson:"bookIds" json:"bookIds"`
	Books   []*Book             `bson:"books" json:"books,omitempty"`
}

type PublisherInput struct {
	Name     string `json:"name"`
	Location string `json:"location"`
}

type Query struct {
}
